<a href="https://colab.research.google.com/github/borneomh/DataMining/blob/main/prepocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


Library Numpy => Olah numerik di pytoh
Library

In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['England' 41.0 73000.0]
 ['Spain' 28.0 49000.0]
 ['Germany' 34.0 44000.0]
 ['Spain' 39.0 62000.0]
 ['Germany' 40.0 nan]
 ['England' 35.0 58000.0]
 ['Spain' nan 53000.0]
 ['England' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['England' 37.0 67000.0]
 ['Germany' nan 64500.0]
 ['Spain' 43.0 nan]
 ['Germany' 41.0 nan]
 ['Spain' 44.0 58000.0]
 ['England' nan 50000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'No' 'No']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
print(x)

[['England' 41.0 73000.0]
 ['Spain' 28.0 49000.0]
 ['Germany' 34.0 44000.0]
 ['Spain' 39.0 62000.0]
 ['Germany' 40.0 61708.333333333336]
 ['England' 35.0 58000.0]
 ['Spain' 40.0 53000.0]
 ['England' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['England' 37.0 67000.0]
 ['Germany' 40.0 64500.0]
 ['Spain' 43.0 61708.333333333336]
 ['Germany' 41.0 61708.333333333336]
 ['Spain' 44.0 58000.0]
 ['England' 40.0 50000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder='passthrough')
x = np.array (ct.fit_transform(x))

In [8]:
print(x)

[[1.0 0.0 0.0 41.0 73000.0]
 [0.0 0.0 1.0 28.0 49000.0]
 [0.0 1.0 0.0 34.0 44000.0]
 [0.0 0.0 1.0 39.0 62000.0]
 [0.0 1.0 0.0 40.0 61708.333333333336]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 40.0 53000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 40.0 64500.0]
 [0.0 0.0 1.0 43.0 61708.333333333336]
 [0.0 1.0 0.0 41.0 61708.333333333336]
 [0.0 0.0 1.0 44.0 58000.0]
 [1.0 0.0 0.0 40.0 50000.0]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1 1 0 1 0 0]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [12]:
print(x_train)

[[0.0 1.0 0.0 34.0 44000.0]
 [0.0 1.0 0.0 40.0 64500.0]
 [0.0 1.0 0.0 40.0 61708.333333333336]
 [0.0 0.0 1.0 28.0 49000.0]
 [0.0 0.0 1.0 44.0 58000.0]
 [1.0 0.0 0.0 41.0 73000.0]
 [1.0 0.0 0.0 40.0 50000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 41.0 61708.333333333336]
 [0.0 0.0 1.0 43.0 61708.333333333336]
 [1.0 0.0 0.0 35.0 58000.0]]


In [13]:
print(x_test)

[[0.0 0.0 1.0 39.0 62000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 40.0 53000.0]]


In [14]:
print(y_train)

[0 1 1 1 0 0 0 1 0 1 0 1]


In [15]:
print(y_test)

[0 1 0]


In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [17]:
print(x_train)

[[0.0 1.0 0.0 -1.0222602785838923 -1.6627617779540311]
 [0.0 1.0 0.0 0.11008956846288122 0.34602593169209034]
 [0.0 1.0 0.0 0.11008956846288122 0.07247150781751711]
 [0.0 0.0 1.0 -2.154610125630666 -1.1728135560891235]
 [0.0 0.0 1.0 0.8649894664940636 -0.29090675673228966]
 [1.0 0.0 0.0 0.29881454297067683 1.1789379088624334]
 [1.0 0.0 0.0 0.11008956846288122 -1.0748239117161418]
 [1.0 0.0 0.0 -0.45608535506050557 0.5910000426245442]
 [0.0 1.0 0.0 1.9973393135408373 2.158834352592249]
 [0.0 1.0 0.0 0.29881454297067683 0.07247150781751711]
 [0.0 0.0 1.0 0.676264491986268 0.07247150781751711]
 [1.0 0.0 0.0 -0.8335353040760968 -0.29090675673228966]]


In [18]:
print(x_test)

[[0.0 0.0 1.0 -0.07863540604491438 0.1010518207596365]
 [1.0 0.0 0.0 1.619889364525246 1.7668757751003226]
 [0.0 0.0 1.0 0.11008956846288122 -0.7808549785971973]]
